feat(media-management): add image resizing
flyacts/backend pull request #23
Opened 2020-10-26 13:29 UTC by zetamorph

2020-10-27 07:00 UTC, enko requested changes
In the grand scheme of things, this looks very good.

I commented one minor nitpick for better readability.

2020-10-27 07:00 UTC, enko commented on packages/media-management/src/providers/file-upload.provider.ts
> +        })?.variants;
I did not find it obvious on the first read what this function does, mostly because `Array.prototype.find` is uncommon.

I would have done it this way:

```typescript
        for (const type of config.types) {
            const isValidForEntity =
                relatedEntity instanceof type.validForEntity;
            
            if (
                typeof type.validForCollections === 'undefined' ||
                type.validForCollections.length === 0
            ) {
                return type.variants;
            }
            
            const isValidForCollection =
                typeof collection === 'string' &&
                type.validForCollections?.includes(collection);
            
            if (isValidForEntity && isValidForCollection) {
                return type.variants;
            }
        }
```

This makes the code in my opinion more readable, because you can scan for return and see immediately what is being returned and then work from there.

2020-10-27 08:27 UTC, zetamorph commented on packages/media-management/src/providers/file-upload.provider.ts
> +        })?.variants;
:+1:

2020-10-28 07:55 UTC, enko commented on packages/media-management/src/providers/media-action.provider.ts
> +                    throw new Error(`Media action ${type} is not available`);
If you have time, it would be nice if you could create a custom errors like https://github.com/flyacts/backend/blob/master/packages/media-management/src/errors/file-not-found.error.ts and throw it. This allows better checking for the error and does not rely on string string operations:

```typescript
if (error instanceof MediaActionNotAvailableError) {
	dostuff();
}
```

2020-10-28 09:02 UTC, zetamorph commented on packages/media-management/src/providers/media-action.provider.ts
> +                    throw new Error(`Media action ${type} is not available`);
good point :+1:

2020-10-28 09:07 UTC, enko approved these changes

2020-10-28 09:08 UTC, merged